spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/art_sharing?verifyServerCertificate=false&useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://jaehodb.cwa8drqjuwbz.ap-northeast-2.rds.amazonaws.com:3306/art_sharing?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

#    username: hongyj
    username: root
#    password: sec031031!
    password: 1q2w3e4r!


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB


resources:
  image-locations: C:\artSharing\
  image-url: 127.0.0.1:8080
#  image-locations : /home/ubuntu/ec2-user/img/
#  image-url : 142.63.193.106:8080

cloud:
  aws:
    s3:
      bucket : jaehobucket
      dirName: artSharing
    region:
      static: ap-northeast-2
    stack:
      auto: false