spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/art_sharing?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://jaehodb.cmokv5cfhdtd.us-east-2.rds.amazonaws.com:3306/art-sharing?verifyServerCertificate=false&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

#    username: hongyj
    username: jpa_user
#    password: sec031031!
    password: jpa_user


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB

resources:
  image-locations : C:\artSharing\
  image-url : 127.0.0.1:8080

